### ISSUE TITLE
I don't like it

### ISSUE THREAD

**Issue by DoubleAPowerBox** [DoubleAPowerBox/stuff#1]
I don't like how this code is looking at me. Not one bit.

**Comment by Grace0Hud** [comment]
understandable, how bout i help you with that. Could you assign this issue to me?

**Comment by DoubleAPowerBox** [comment]
Bam. Now punch it in the face or something.

**Comment by Grace0Hud** [comment]
i gotchu

**Comment by DoubleAPowerBox** [comment]
All done! Thanks!
